### ISSUE TITLE
Tytuł

### ISSUE THREAD

**Issue by MonikaKrol** [Marczew/Bomberman#1]
Ustalenie tytułu aplikacji. Na ten moment coś podobnego do: "Bomber Man". Zalecana konsultacja z resztą zespołu, ale to **SK** ostatecznie decyduje.

**UWAGA**: Ostateczne ustalenie nazwy gry należy zapisać w raporcie wraz z ów nazwą oraz przesłać **AS**, odpowiedzialnemu za opracowanie aktualnego sprintu.

**Comment by INGPstakra** [comment]
bombman?

**Comment by INGPstakra** [comment]
Tak więc zostaje BombMan
