### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by MonikaKrol** [Marczew/Bomberman#2]
Opracowanie graficzne loga naszej gry, czyli czegoś, przez co będziemy rozpoznawalni. Powinno rzucać się w oczy (generalnie przykuwać uwagę użytkownika, wzbudzać ciekawość), jednoznacznie kojarzyć się z grą, którą reprezentuję i jednocześnie być w miarę proste.

**SK** może zlecić wykonanie tego zadania (od strony graficznej) komuś innemu, ale to właśnie on decyduję o ostatecznym logo produktu.

**UWAGA**: Należy w raporcie podać informację o użytym programie graficznym (np. Gimp) i jego kosztach (koszt może być równy zero przy programach typu open source - CHOCIAŻ przy użytku komercyjnym należy zapłacić za ów program).

**Comment by INGPstakra** [comment]
myślałem o zwykłej czarnej bombie z palącym się knotem i jeśli nie macie nic przeciwko nazwie bombman to można napisać na niej BM?

**Comment by INGPstakra** [comment]
coś koło tego
![czarne kolo](https://cloud.githubusercontent.com/assets/27808190/25715495/f01b6ff6-30fb-11e7-8471-d5e52f5c6fec.png)

**Comment by MonikaKrol** [comment]
Moim zdaniem spoko, ale chyba powinieneś poprawić kolorystykę, bo tych liter "BM" prawie nie widać ;)

**Comment by INGPstakra** [comment]
odnośnie tego nie jestem dobry jeśli chodzi o elementy graficzne, więc szukam chętnego do tego
a ten rysunek to tylko propozycja jak ma to wyglądać

**Comment by INGPstakra** [comment]
![image](https://cloud.githubusercontent.com/assets/27808190/25845392/023b5146-34ae-11e7-88a9-7843923062ad.png)

**Comment by INGPstakra** [comment]
co wy na taką bombę

**Comment by INGPstakra** [comment]
![bombka](https://cloud.githubusercontent.com/assets/27808190/25886453/eb96be84-355d-11e7-9ae1-cedef460ec8f.png)

**Comment by INGPstakra** [comment]
coś takiego?

**Comment by MonikaKrol** [comment]
Moim zdaniem lepsze (kolorystyka) byłyby ciemnoczerwone litery :)! Jeszcze pogrubione i z kursywą.
![bm](https://cloud.githubusercontent.com/assets/27808195/26024482/51ea8ef6-37d2-11e7-855b-b91e2ffce7c6.png)

**Comment by INGPstakra** [comment]
jutro zrobię ankietę z wyborem bomby i poświatą, czcionką i innymi efektami i wyśle link na fb
zapytam jeszcze siostry co o tym myśli i zdecyduje w poniedziałek

**Comment by INGPstakra** [comment]
![bombkadlamoniki](https://cloud.githubusercontent.com/assets/27808190/26071050/11652d56-39a7-11e7-871e-1b69ac352a42.png)
![bombkadlamarcina](https://cloud.githubusercontent.com/assets/27808190/26071055/1407b56a-39a7-11e7-9da9-9b3e439c1238.png)

**Comment by INGPstakra** [comment]
![special](https://cloud.githubusercontent.com/assets/27808190/26071187/81192d6e-39a7-11e7-8074-684a768acbd7.png)

**Comment by INGPstakra** [comment]
https://drive.google.com/open?id=1qnXRUlMWhmiktJW88tdkVw-A2ufPx_BwUYsp5DyAN1U

**Comment by INGPstakra** [comment]
Decyzja została podjęta i ta bombka została wybrana
![bombkadlamarcina](https://cloud.githubusercontent.com/assets/27808190/26140515/98202d1a-3ad7-11e7-9e5e-afaada5a0ed6.png)
